name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  test:
    name: Run test-unit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version:
        - "2.5"
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"
        - "3.2"
        exclude:
        - os: macos-latest
          version: "2.5"
        include:
        - os: macos-13
          version: "2.5"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
